### PR TITLE
Quality of life changes and fixes #14

### LINKED ISSUE #14: Final modal broken on mobile
### Overview
- Final modal was not tested on mobile using 512x512 images
- The final modal is now awkward and causes scrolling on mobile

### Screenshot
image

### LINKED ISSUE #16: Increase site content while page loading
### Overview

- People (recruiters) may click off on the initial load because our lambda server is slow on cold start
- Show the photo queue + buttons before the images are returned, to keep user engaged

### Example
image

### Current
image

### LINKED ISSUE #21: Make animated logo
- make an animate logo using the beaker

### PR DESCRIPTION
**Pull request by zachale**
###Overview
- Fixed the final modal being broken on mobile (closes #14)
- Fixed some small key-related console errors
- Added new perfect score text
- Added new testing mode for imageBackend
- Added animate logo (closes #21)
- Cleaned up loading screen (closes #16 )

Imaginate #24
🟩🟩🟩🟩🟩✨

###Screenshots
image

loadingimaginate

### CODE REVIEW

File: src/services/imageBackend.ts [hunk 1]
```diff
@@ -1,21 +1,28 @@
+import { testImages } from '../testData';
```
Comment (faisal-fawad) [inline src/services/imageBackend.ts]: This import does not work due to your updated .gitignore hence the failing Nelify build / deploy

**Review by faisal-fawad — APPROVED** [review]
See below for quick note, otherwise, LGTM

**Review by faisal-fawad — APPROVED** [review]
